#!/usr/bin/env/ bash

# Build script to copy distribution version of plugin to test WordPress site on local dev server.

# Files to ignore:
# /node_modules
# composer*
# package*

# Run Gulp Build File
npx gulp

# Copy distribution files built by gulp into corresponding plugin folder.
cp -ur dist/* /c/xampp/htdocs/j8ahmed_wordpress_blog/wp-content/plugins/j8ahmed-test-plugin-1/
